export { default as ProfileSettings } from './ProfileSettings'
export { default as SecuritySettings } from './SecuritySettings'
export { default as NotificationSettings } from './NotificationSettings'
export { default as AppearanceSettings } from './AppearanceSettings'
export { default as LanguageSettings } from './LanguageSettings'
export { default as PrivacySettings } from './PrivacySettings'
