#!/bin/bash
echo "=== TESTE DNS FLIPCARS.US ==="
echo ""
echo "1. Testando webmail.flipcars.us:"
nslookup webmail.flipcars.us 8.8.8.8 2>&1 || echo "ERRO: não resolve"
echo ""
echo "2. Testando mail.flipcars.us:"
nslookup mail.flipcars.us 8.8.8.8 2>&1 || echo "ERRO: não resolve"
echo ""
echo "3. Testando MX record flipcars.us:"
nslookup -type=MX flipcars.us 8.8.8.8 2>&1 || echo "ERRO: não resolve"
echo ""
echo "4. Testando ping webmail.flipcars.us:"
ping -c 2 webmail.flipcars.us 2>&1 || echo "ERRO: não responde"
