import { Appointment, AppointmentStatus } from '@/lib/api/appointments.service';

/**
 * Test appointment data for calendar visualization
 * Based on mockup structure (lines 2990-3048)
 */
export const TEST_APPOINTMENTS: Appointment[] = [
  // November 8, 2025
  {
    id: 'test-appt-1',
    leadId: 'test-lead-1',
    appointmentDate: '2025-11-08',
    appointmentTimeSlot: '9:00-11:00',
    appointmentStartTime: '09:00:00',
    appointmentEndTime: '11:00:00',
    status: AppointmentStatus.SCHEDULED,
    notes: 'Body repair - Insurance claim',
    createdAt: new Date('2025-11-01').toISOString(),
    updatedAt: new Date('2025-11-01').toISOString(),
    lead: {
      id: 'test-lead-1',
      referenceNumber: 'FLIP-20251108-0001',
      name: 'Bob Johnson',
      phone: '(555) 123-4567',
      email: 'bob.johnson@email.com',
      vehicleYear: '2019',
      vehicleMake: 'Honda',
      vehicleModel: 'Civic',
      hasInsurance: true,
      insuranceProvider: 'Progressive',
      priority: 'medium',
      status: 'active',
      estimatedValue: 2500.00,
    },
  },

  // November 12, 2025
  {
    id: 'test-appt-2',
    leadId: 'test-lead-2',
    appointmentDate: '2025-11-12',
    appointmentTimeSlot: '10:00-12:00',
    appointmentStartTime: '10:00:00',
    appointmentEndTime: '12:00:00',
    status: AppointmentStatus.CONFIRMED,
    notes: 'Paint job follow-up',
    createdAt: new Date('2025-11-03').toISOString(),
    updatedAt: new Date('2025-11-03').toISOString(),
    lead: {
      id: 'test-lead-2',
      referenceNumber: 'FLIP-20251112-0001',
      name: 'Maria Garcia',
      phone: '(321) 456-7890',
      email: 'maria.garcia@email.com',
      vehicleYear: '2019',
      vehicleMake: 'Honda',
      vehicleModel: 'Accord',
      hasInsurance: false,
      priority: 'high',
      status: 'active',
      estimatedValue: 750.00,
    },
  },

  // November 14, 2025
  {
    id: 'test-appt-3',
    leadId: 'test-lead-3',
    appointmentDate: '2025-11-14',
    appointmentTimeSlot: '14:00-16:00',
    appointmentStartTime: '14:00:00',
    appointmentEndTime: '16:00:00',
    status: AppointmentStatus.SCHEDULED,
    notes: 'Oil change + inspection',
    createdAt: new Date('2025-11-05').toISOString(),
    updatedAt: new Date('2025-11-05').toISOString(),
    lead: {
      id: 'test-lead-3',
      referenceNumber: 'FLIP-20251114-0001',
      name: 'Robert Williams',
      phone: '(407) 789-0123',
      email: 'robert.w@email.com',
      vehicleYear: '2021',
      vehicleMake: 'Ford',
      vehicleModel: 'F-150',
      hasInsurance: false,
      priority: 'low',
      status: 'active',
      estimatedValue: 120.00,
    },
  },

  // November 15, 2025
  {
    id: 'test-appt-4',
    leadId: 'test-lead-4',
    appointmentDate: '2025-11-15',
    appointmentTimeSlot: '9:00-10:30',
    appointmentStartTime: '09:00:00',
    appointmentEndTime: '10:30:00',
    status: AppointmentStatus.CONFIRMED,
    notes: 'Transmission repair consultation',
    createdAt: new Date('2025-11-06').toISOString(),
    updatedAt: new Date('2025-11-06').toISOString(),
    lead: {
      id: 'test-lead-4',
      referenceNumber: 'FLIP-20251115-0001',
      name: 'Jennifer Martinez',
      phone: '(407) 987-3451',
      email: 'jennifer.m@email.com',
      vehicleYear: '2020',
      vehicleMake: 'BMW',
      vehicleModel: '320i',
      hasInsurance: true,
      insuranceProvider: 'State Farm',
      priority: 'high',
      status: 'active',
      estimatedValue: 3200.00,
    },
  },

  // November 17, 2025
  {
    id: 'test-appt-5',
    leadId: 'test-lead-5',
    appointmentDate: '2025-11-17',
    appointmentTimeSlot: '11:00-13:00',
    appointmentStartTime: '11:00:00',
    appointmentEndTime: '13:00:00',
    status: AppointmentStatus.RESCHEDULED,
    notes: 'Bumper replacement',
    createdAt: new Date('2025-11-07').toISOString(),
    updatedAt: new Date('2025-11-08').toISOString(),
    lead: {
      id: 'test-lead-5',
      referenceNumber: 'FLIP-20251117-0001',
      name: 'Michael Chen',
      phone: '(321) 567-8901',
      email: 'michael.chen@email.com',
      vehicleYear: '2018',
      vehicleMake: 'Toyota',
      vehicleModel: 'Camry',
      hasInsurance: true,
      insuranceProvider: 'Geico',
      priority: 'medium',
      status: 'active',
      estimatedValue: 1800.00,
    },
  },

  // Overdue appointment (November 3, 2025)
  {
    id: 'test-appt-overdue-1',
    leadId: 'test-lead-overdue-1',
    appointmentDate: '2025-11-03',
    appointmentTimeSlot: '10:00-12:00',
    appointmentStartTime: '10:00:00',
    appointmentEndTime: '12:00:00',
    status: AppointmentStatus.SCHEDULED,
    notes: 'OVERDUE - Needs follow-up',
    createdAt: new Date('2025-10-25').toISOString(),
    updatedAt: new Date('2025-10-25').toISOString(),
    lead: {
      id: 'test-lead-overdue-1',
      referenceNumber: 'FLIP-20251103-0001',
      name: 'John Doe',
      phone: '(888) 221-3982',
      email: 'john.doe@email.com',
      vehicleYear: '2021',
      vehicleMake: 'Mitsubishi',
      vehicleModel: 'Outlander',
      hasInsurance: false,
      priority: 'high',
      status: 'active',
      estimatedValue: 4500.00,
    },
  },

  // Another overdue appointment (November 5, 2025)
  {
    id: 'test-appt-overdue-2',
    leadId: 'test-lead-overdue-2',
    appointmentDate: '2025-11-05',
    appointmentTimeSlot: '14:00-16:00',
    appointmentStartTime: '14:00:00',
    appointmentEndTime: '16:00:00',
    status: AppointmentStatus.SCHEDULED,
    notes: 'OVERDUE - Customer not responding',
    createdAt: new Date('2025-10-28').toISOString(),
    updatedAt: new Date('2025-10-28').toISOString(),
    lead: {
      id: 'test-lead-overdue-2',
      referenceNumber: 'FLIP-20251105-0001',
      name: 'Maria Silva',
      phone: '(844) 945-0938',
      email: 'maria.silva@email.com',
      vehicleYear: '2020',
      vehicleMake: 'Ford',
      vehicleModel: 'EcoSport',
      hasInsurance: false,
      priority: 'medium',
      status: 'active',
      estimatedValue: 1200.00,
    },
  },
];

/**
 * Flag to enable/disable test data in components
 */
export const USE_TEST_DATA = false;
